name: GitHub Actions Build an Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-an-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-actions@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
